version: '2'

services:
  web:
    build: .
    command: python3 main.py
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: db
    hostname: db
    ports:
      - 5432:5432
    volumes:
      - /Users/ihor:/var/lib/postgresql
    environment:
      POSTGRES_USER: ihor
      POSTGRES_PASSWORD: 140697
      POSTGRES_DB: tech




