version: '2'

services:
  web:
    build: .
    command:
      - python model.py
      - python main.py
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ihor
      POSTGRES_PASSWORD: 140697
      POSTGRES_DB: tech_task






